#!/usr/bin/env python3
"""Regenerate words.js and words-extra.json.

    python3 tools/build-words.py [--no-scrabble]

Three tiers, because they are not equally likely to be the answer:

  words.js        SKRIBBL_WORDS  -- words scraped from skribbl's own list.
                  The game picks from this, so these outrank everything.

  words-extra.json  .good -- common/drawable English that skribbl
                  itself does not use. Plausible in a custom-word room.
                  Ordered by frequency, so the likely ones come first.

                    .rest -- the rest of the Scrabble dictionary.
                  Total coverage, but note it holds no proper nouns, brands or
                  memes, which is what custom rooms actually tend to use.

Both extra tiers are bucketed by word length and stored as newline-joined
strings: the panel splits one bucket on demand, so a 260k-word dictionary costs
nothing until a round needs that exact length.

Sources (the skribbl ones are committed under tools/sources; the big
dictionaries are downloaded and cached in /tmp):
  tools/sources/Skribbl-words.csv    gist.github.com/mvark/9e0682c62d75625441f6ded366245203
  tools/sources/skribbl-guesser.csv  github.com/jackkowalik/skribbl-guesser
  scribble.rs en_us + en_gb          github.com/scribble-rs/scribble.rs
  google-10000-english               github.com/first20hours/google-10000-english
  SOWPODS                            github.com/jesstess/Scrabble
"""
import csv, json, os, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(HERE, "sources")
CACHE = "/tmp/skribbl-helper-dicts"

REMOTE = {
    "scribble_us": "https://raw.githubusercontent.com/scribble-rs/scribble.rs/master/internal/game/words/en_us",
    "scribble_gb": "https://raw.githubusercontent.com/scribble-rs/scribble.rs/master/internal/game/words/en_gb",
    "common":      "https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-usa-no-swears.txt",
    "sowpods":     "https://raw.githubusercontent.com/jesstess/Scrabble/master/scrabble/sowpods.txt",
}

MIN_LEN, MAX_LEN = 3, 20


def norm(w):
    return " ".join(w.split()).strip().lower()


def fetch(key):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, key + ".txt")
    if not os.path.exists(path):
        sys.stderr.write("downloading %s ...\n" % key)
        urllib.request.urlretrieve(REMOTE[key], path)
    return [norm(l) for l in open(path, encoding="utf8", errors="replace") if l.strip()]


def read_plain(name):
    p = os.path.join(SRC, name)
    return [norm(l) for l in open(p, encoding="utf8", errors="replace") if l.strip()]


def read_csv(name):
    out = []
    with open(os.path.join(SRC, name), newline="", encoding="utf8", errors="replace") as fh:
        for row in csv.reader(fh):
            if row and row[0].strip() and row[0].strip().lower() != "word":
                out.append(norm(row[0]))
    return out


def ok_single(w):
    # dictionary tiers are single plain words; skribbl's own list may have
    # spaces and punctuation and is not filtered this way
    return w.isalpha() and MIN_LEN <= len(w) <= MAX_LEN


def bucket(words):
    """{length: "word\\nword\\n..."} preserving the order given."""
    out = {}
    for w in words:
        out.setdefault(len(w), []).append(w)
    return {k: "\n".join(v) for k, v in sorted(out.items())}


def main():
    want_scrabble = "--no-scrabble" not in sys.argv

    # ---- tier 1: skribbl's own list, merged across scrapes ----
    tier1, seen = [], set()
    for w in read_csv("Skribbl-words.csv") + read_csv("skribbl-guesser.csv"):
        if w and MIN_LEN <= len(w) <= MAX_LEN and w not in seen:
            seen.add(w)
            tier1.append(w)
    tier1.sort()

    with open(os.path.join(ROOT, "words.js"), "w", encoding="utf8") as fh:
        fh.write("// Generated by tools/build-words.py -- do not edit by hand.\n")
        fh.write("// Words scraped from skribbl.io's own list; the game picks from these.\n")
        fh.write("const SKRIBBL_WORDS = %s;\n" % json.dumps(tier1, ensure_ascii=False))

    # ---- tier 2: common + drawable English skribbl does not use ----
    common = [w for w in fetch("common") if ok_single(w) and w not in seen]
    good, gseen = [], set()
    for w in common:                                   # frequency order first
        if w not in gseen:
            gseen.add(w)
            good.append(w)
    drawable = sorted(set(w for w in fetch("scribble_us") + fetch("scribble_gb")
                          if ok_single(w) and w not in seen and w not in gseen))
    good.extend(drawable)
    gseen.update(drawable)

    # ---- tier 3: the rest of the Scrabble dictionary ----
    rest = []
    if want_scrabble:
        rest = sorted(set(w for w in fetch("sowpods")
                          if ok_single(w) and w not in seen and w not in gseen))

    # JSON, not JS: this is fetched on demand rather than bundled into the
    # content script, so a normal round never pays to load it.
    extra = {"good": bucket(good), "rest": bucket(rest)}
    with open(os.path.join(ROOT, "words-extra.json"), "w", encoding="utf8") as fh:
        json.dump(extra, fh, ensure_ascii=False)

    size = lambda p: os.path.getsize(os.path.join(ROOT, p))
    print("words.js        %7d words  %8.1f KB" % (len(tier1), size("words.js") / 1024))
    print("words-extra.json  good %6d / rest %6d  %8.1f KB (fetched on demand)"
          % (len(good), len(rest), size("words-extra.json") / 1024))


if __name__ == "__main__":
    main()
